### PR TITLE
Add missing bits of wiring / docs

### PR DESCRIPTION
**Pull request by petemounce**
I noticed a few gaps, so plugged them.

### CODE REVIEW

**Comment by jinsyaoommen** [comment]
@petemounce - CI test failed. 
Thanks!

**Comment by petemounce** [comment]
@jinsyaoommen there you go. Is there anything further that needs to happen before merge?

**Comment by jinsyaoommen** [comment]
@petemounce - I merged the elasticsearch pull request, could you please look at the merge conflict on this pr? Thanks much for your contribution! We'll get it merged after the conflict has been resolved.

**Comment by petemounce** [comment]
Hi @jinsyaoommen - I pulled from master, then rebased that into this branch, then force-pushed here. It looks like the work I'd done had already happened on master, so GH noticed and closed this.

**Pull request closed without merging**
