### PR TITLE
SEN-1540 -- Add Kinesis to AWS Promised

### PR DESCRIPTION
**Pull request by cberube**

### CODE REVIEW

**Comment by nackjicholson** [comment]
:ok: :shipit: Do you want to `npm publish` ?

**Comment by jinsyaoommen** [comment]
:ok:

**Comment by cberube** [comment]
Feel free to review this, but please hold off on merging so I don't loose track of doing an NPM publish -- thanks!

**Comment by nwarlen** [comment]
:ok: :shipit:

**Pull request merged**
