### PR TITLE
Update memoize call for all services to use JSON.stringify

### LINKED ISSUE #12: Memoize causes fetching the same configured instance on several EC2 creations
I was having this issue yesterday: http://stackoverflow.com/questions/32015345/data-returned-from-promises-with-aws-sdk-for-node-and-bluebird

And finally I found out what was causing it.

It may be that I don't understand properly why memoize is being used here, but, from what I understood, if I create an EC2-promised instance with a concrete configuration, like follows:

`var AWS = require('aws-promised'),
      ec2 = AWS.ec2({region: 'us-east-1'});`

If later on I need to create new EC2 instances with different regions configurations, simply because I could maybe request data per each region, by having memoize there what I get is a new instance with the previous configuration, which is wrong.

By commenting out the memoization on this file: https://github.com/davidpelayo/aws-promised/blob/master/ecs.js at the end, I get the expected results, as posted in the stackoverflow issue.

Could you elaborate why this would be happening, why memoize would be needed here and what the alternatives would be to solve my issues if there is any?

Thanks in advance.

### PR DESCRIPTION
**Pull request by cberube**
This change should resolve the issue with the memoize function failing to correctly recognize changes to the AWS configuration object.

Fixes #12

### CODE REVIEW

**Comment by nackjicholson** [comment]
:ok: :shipit: Thanks for fixing that test to catch it, looks good.

**Comment by nwarlen** [comment]
:ok:

**Comment by cberube** [comment]
Seems like this change should go into a version `2.6.1` -- any other thoughts about where it belongs?

**Comment by nackjicholson** [comment]
That makes sense to me. `npm version patch`

**Pull request merged**
